name: Build rmw_zenoh_dynamic_cpp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install missing dependencies
      run: |
        sudo apt update
        wget -O /tmp/ecal.deb https://github.com/continental/ecal/releases/download/v5.7.5/ecal_5.7.5-focal_amd64.deb
        sudo apt install -y /tmp/ecal.deb
        sudo apt install -y libc6 libcurl4 libgcc1 libhdf5-103 libqt5core5a libqt5gui5 libqt5widgets5 libstdc++6
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install \
          --default-yes \
          --from-paths rmw_zenoh_dynamic_cpp \
          --ignore-src \
          --rosdistro foxy

    - name: Build
      run: |
        . /opt/ros/foxy/setup.sh
        colcon build \
          --event-handlers console_cohesion+ \
          --packages-up-to rmw_zenoh_dynamic_cpp

    - name: Run tests
      run: |
        . /opt/ros/foxy/setup.sh
        colcon test \
          --return-code-on-test-failure \
          --event-handlers console_cohesion+ \
          --packages-up-to rmw_zenoh_dynamic_cpp
